root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "tailwindcss -i public/tailwind.css -o public/styles.css && go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["tmp", "vendor", "bin", "testdata", "node_modules", "public", "htmx-go"]
  exclude_file = ["Makefile", "dev.sh", "package.json", "htmx-go.db"]
  exclude_regex = ["_test.go", "htmx-go.db-shm", "htmx-go.db-wal"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
